export const ErrorCode = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_API_KEY: "INVALID_API_KEY",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  USER_MUST_BE_18_OR_OLDER: "USER_MUST_BE_18_OR_OLDER",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  WRONG_PASSWORD_ERROR: "WRONG_PASSWROD_ERROR"
}
